name: Deploy to Ubuntu VM

on:
  push:
    branches:
      - mytry2

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy code
        run: |
          ssh -o "StrictHostKeyChecking=no" marc@49.149.130.81 "cd /home/marc && git pull origin mytry2"
