name: Deploy to Ubuntu VM

on:
  pull_request:
    types: [closed]
    branches:
      - main
    if: github.event.pull_request.merged == true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy code
        run: |
          C:\OpenSSH-Win64\ssh.exe -i C:\Users\lemuel/.ssh/id_rsa/qwe.txt marc@49.149.130.81 "cd /home/marc && git pull origin mytry2"
