name: Deploy on Merge to Ubuntu

on:
  pull_request:
    types:
      - closed
      - merged

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
#    - name: Read SSH password from file
   #   run: export SSH_PASSWORD=$(cat /etc/ssh/sshpw.txt)
    - name: Copy files to remote server using SCP
      run: scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null . marc@192.168.0.116:/home/marc/
      env:
        SSH_PASSWORD: ${{ env.SSH_PASSWORD }}
