name: Deploy on Merge to Ubuntu

on:
  pull_request:
    types:
      - closed
      - merged

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Copy files to remote server using SCP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        hostname: 192.168.0.116
        username: marc
        password: ${{ secrets.SSH_PASSWORD }}
        source: "./"
        target: "/home/marc/"
        port: 22
