name: Deploy to DigitalOcean
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        run: |
          sudo snap install doctl

      - name: Deploy to droplet
        uses: digitalocean/action-doctl@v2
        with:
          command: compute scp --recursive --ssh-port 22 --local-path . root@188.166.240.21:/root --password m4Rtinez
