name: Deploy on Merge to Ubuntu

on:
  pull_request:
    types:
      - closed
      - merged

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Delete old cloned repository
      run: rm -rf ~/cicd1
    - name: Clone repository
      run: git clone https://github.com/marcmarion13/cicd1.git ~/cicd1
    - name: Copy files to remote server using SCP
      uses: appleboy/scp-action@master
      with:
        host: 192.168.0.116
        username: marc
        key: ${{ secrets.SSH_PASSWORD }}
        source: ~/cicd1/
        target: /home/marc/
