name: Deploy on Merge to Ubuntu

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Ubuntu
      uses: appleboy/ssh-action@v2.3.0
      with:
        host: 192.168.0.116
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd ~/Desktop/fromgi
          rm -rf *
          scp -r ./* user@192.168.0.116:~/Desktop/fromgi
