name: Deploy on Merge to Ubuntu

on:
  pull_request:
    types:
      - closed
      - merged

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Create directory if it does not exist
      run: |
        if (!(Test-Path ~/cicd1)) {
          New-Item -ItemType Directory -Path ~/cicd1
        }
    - name: Delete old cloned repository
      run: Remove-Item -Recurse -Force ~/cicd1
    - name: Clone repository
      run: git clone https://github.com/marcmarion13/cicd1.git ~/cicd1
    - name: Copy files to remote server using SCP
      run: scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ~/cicd1/* marc@192.168.0.116:/home/marc/
