name: Deploy on Merge to Ubuntu

on:
  pull_request:
    types:
      - closed
      - merged

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Copy files to remote server using SCP
      run: scp -v -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./ marc@192.168.0.116:/home/marc/
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
