name: Deploy to Ubuntu VM

on:
  pull_request:
    types: [closed]
    branches:
      - main
    if: github.event.pull_request.merged == true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to DigitalOcean droplet
        uses: digitalocean/action-doctl@v2
        # Replace with your DigitalOcean access token and droplet name
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          command: scp -r ./ root@128.199.129.95:/home/


  
