name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: 128.199.129.95
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /home
          rm -rf *
          rsync -r --delete-after --quiet $GITHUB_WORKSPACE/ .
