name: Deploy on Merge to Ubuntu

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Ubuntu
      uses: appleboy/scp-action@master
      with:
        host: 192.168.0.116
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: ./*
        target: ~/Desktop/fromgi
