name: Auto deploy to DigitalOcean
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install sshpass
      run: runas apt-get install -y sshpass
      
    - name: Deploy to DigitalOcean droplet
      uses: appleboy/scp-action@master
      with:
        host: 188.166.240.21
        username: root
        password: m4Rtinez
        source: ${{ github.workspace }}
        target: /root/fromgithub
