name: Deploy on Merge to Ubuntu

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Ubuntu
      uses: appleboy/ftp-action@v0.2.0
      with:
        server: 192.168.0.116
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        protocol: ftp
        local-dir: "./"
        server-dir: "~/Desktop/fromgi/"
        port: 21
